---
apiVersion: v1                              # API group
kind: Service                               # Kubernetes Resource Type
metadata:
  name: catalog-service                     # Name of the Service
  labels:
    app.kubernetes.io/name: catalog         # Label used for identification and grouping (also help with Filtering, debugging, linking, dashboards)
spec:
  type: ClusterIP                           # Default service type; exposes service internally within the cluster
  selector:
    app.kubernetes.io/name: catalog         # Targets Pods with this label (links Service → Pods). Should match with my deployment selector matchlabels
  ports:
    - name: http                            # Logical name for the port
      port: 8080                            # Port exposed inside the cluster (Service port)
      targetPort: 8080                      # Port on the container that receives traffic
      protocol: TCP                         # Protocol used for communication
