---
# https://www.base64encode.org/

apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
data:
  CATALOG_PERSISTENCE_USER: "Y2F0YWxvZ3VzZXI="
  CATALOG_PERSISTENCE_PASSWORD: "TWFwbGVTaGFkZU5KMDgwNTI="