apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-db-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: us-east-2
    usePodIdentity: "true"
    objects: |
      - objectName: "catalog-db-secret-1"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MYSQL_USER"
            objectAlias: "MYSQL_USER"
          - path: "MYSQL_PASSWORD"
            objectAlias: "MYSQL_PASSWORD"
    
  secretObjects:
    - secretName: orders-db
      type: Opaque
      data:
        - objectName: MYSQL_USER
          key: RETAIL_ORDERS_PERSISTENCE_USERNAME
        - objectName: MYSQL_PASSWORD
          key: RETAIL_ORDERS_PERSISTENCE_PASSWORD