apiVersion: secrets-store.csi.x-k8s.io/v1   # API version for Secrets Store CSI Driver
kind: SecretProviderClass                  # Resource type that defines how to fetch external secrets

metadata:
  name: catalog-db-secrets                 # Name of the SecretProviderClass (referenced by pods)

spec:
  provider: aws                           # Specifies AWS as the external secret provider

  parameters:
    objects: |                            # List of secrets to fetch from AWS Secrets Manager
      - objectName: "catalog-db-secret-1" # Name of the secret in AWS Secrets Manager
        objectType: "secretsmanager"      # Type of AWS service (Secrets Manager)

        jmesPath:                         # Used to extract specific fields from the secret JSON
          - path: "MYSQL_USER"            # Key in the secret JSON
            objectAlias: "MYSQL_USER"     # File name created inside the container
          
          - path: "MYSQL_PASSWORD"        # Another key in the secret JSON
            objectAlias: "MYSQL_PASSWORD" # File name created inside the container

    usePodIdentity: "true"                # Enables EKS Pod Identity for authentication
                                          # No need for IAM roles on nodes or static credentials