# Source: retail-store-sample-catalog-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "Y2F0YWxvZ3VzZXI="
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "TWFwbGVTaGFkZU5KMDgwNTI="
