---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cli-sa          # Name of the ServiceAccount that my pod will use
  namespace: default        # Namespace where the ServiceAccount will live
